import Head from "next/head";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import Skills from "./components/Skills";
import Image from "next/image";
import porto1 from "../public/porto1.png";
import porto2 from "../public/porto2.png";
import porto3 from "../public/porto3.png";
import porto4 from "../public/porto4.png";
import { Inter } from "next/font/google";
import Intro from "./components/Intro";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-slate-200">
      <Head>
        <title>Andika Satrio Portofolio</title>
        <meta name="description" content="Generated by next" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="px-10">
        <Intro />
        <Skills />
        <section>
          <div id="projects">
            <h3 className="py-1 text-3xl">Projects</h3>
            <p className="py-5 leading-8 text-gray-500 text-md">
              These are some projects that I have done to show case my skills
              and studies.
            </p>
          </div>
          <div className="gap-5 text-gray-500 cursor-pointer porto lg:flex">
            <div className="m-5">
              <h3>Weather App</h3>
              <Image src={porto1} className="rounded-lg" width={"100%"} />
            </div>
            <div className="m-5">
              <h3>Book List App</h3>
              <Image src={porto2} className="rounded-lg" width={"100%"} />
            </div>
            <div className="m-5">
              <h3>MERN Personal Blog</h3>
              <Image src={porto3} className="rounded-lg" width={"100%"} />
            </div>
            <div className="m-5">
              <h3>Promptia AI sharing snippet</h3>
              <Image src={porto4} className="rounded-lg" width={"100%"} />
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
